export interface Content {
  id: number,
  typeTitle: string,
  type: string,
  link: string,
  detailsImg: string,
  category: string,
  author: string,
  tag: [],
  landing: boolean,
  trending: boolean,
  description: string,
  contentTitle: string,
  media: string,
  mediaCaption: string,
  contentAbove: string,
  contentBelow: string,
  status: string,
  slides: [],
}
